### ISSUE TITLE
feat(Session): implement session

### ISSUE THREAD

**Issue by chanhihi** [MyLittleWebServer/webserv#176]
session에 대해서 구현합니다.

session management

**Comment by chanhihi** [comment]
@Clearsu @middlefitting @cjho0316 

- Support cookies and session management (prepare quick examples).

보너스 항목에 대해서 살펴보자면 cookies를 지원 그리고 세션 관리 기술을 지원하라고 합니다.
그리고 예제를 준비하면 될것 같습니다. 

쿠키만 구현 하면 될 것 같은데, 여러분의 생각은 어떠신지 궁금합니다.

---

세션 관리 기술에 대해서 살펴보자면 세션 관리 기술에는 여러 가지가 있습니다:

쿠키(Cookies): 쿠키는 클라이언트 측에서 데이터를 저장하는 데 사용되는 작은 데이터 조각입니다. 서버는 HTTP 응답 헤더에 Set-Cookie를 설정하여 쿠키를 클라이언트에 전송하고, 클라이언트는 이후 요청에서 Cookie 헤더에 쿠키를 포함하여 전송합니다. 쿠키는 사용자 세션을 유지하는 데 자주 사용되며, 세션 ID, 사용자 설정, 쇼핑 카트 항목 등을 저장하는 데 사용될 수 있습니다.

세션 저장소(Session Storage): 세션 저장소는 브라우저의 탭 또는 윈도우별로 데이터를 저장합니다. 페이지가 다시 로드되거나 다시 방문되어도 데이터가 유지되지만, 탭이나 윈도우가 닫히면 데이터는 삭제됩니다.

로컬 저장소(Local Storage): 로컬 저장소는 브라우저 전체에 걸쳐 데이터를 저장합니다. 데이터는 영구적이며, 사용자가 브라우저를 닫아도 삭제되지 않습니다. 로컬 저장소는 사용자 설정 또는 장기 로그인 정보와 같은 데이터를 저장하는 데 사용될 수 있습니다.

세션 ID(Session ID): 서버는 각 사용자 세션에 대해 고유한 ID를 생성하여 세션 정보를 추적합니다. 이 세션 ID는 보통 쿠키를 통해 클라이언트에 전송되며, 클라이언트는 이후 요청에서 세션 ID를 제공하여 자신을 식별합니다. 서버는 세션 ID를 사용하여 사용자 정보, 로그인 상태, 쇼핑 카트 항목 등을 저장하고 검색하는 데 사용하는 세션 저장소를 유지합니다.

세션 관리는 사용자 인증, 개인화된 사용자 경험, 보안 등 많은 웹 애플리케이션 기능을 가능하게 합니다. 그러나 세션 데이터의 보안과 개인 정보 보호를 위해 적절한 측정을 취해야 합니다.

**Comment by Clearsu** [comment]
제 생각에는 올려주신 부분은 위 모두가 필요하다는 취지의 설명인 것 같습니다.

추가로, 읽어보시면 설계에 도움이 되실 것 같습니다.

https://velog.io/@won-developer/%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EA%B5%AC%ED%98%84-%EC%BF%A0%ED%82%A4%EC%99%80-%EC%84%B8%EC%85%98-n3wwrtip
