### ISSUE TITLE
Vscode Code Formatting 설정

### ISSUE THREAD

**Issue by middlefitting** [MyLittleWebServer/webserv#2]
해당 프로젝트의 코드 스타일을 Google 스타일에 맞춰 설정합니다.

### 방법
> VsCode에서 아래 extensions 설치합니다
<img width="367" alt="image" src="https://github.com/MyLittleWebServer/webserv/assets/76660692/eb58134d-89cc-414a-859a-85759fb7c3d3">
<br/>
<img width="372" alt="image" src="https://github.com/MyLittleWebServer/webserv/assets/76660692/558187a8-cdfa-48ee-b184-b34d2bdea58d">
<br/><br/><br/>

> cmd + shift + p 명령어를 누르고 Setting.json 들어갑니다.
<img width="367" alt="image" src="https://github.com/MyLittleWebServer/webserv/assets/76660692/6c76698a-d2d8-43ea-b72f-fddde002fd16">
<br/><br/><br/>

> 아래 설정을 추가합니다

"editor.defaultFormatter": "ms-vscode.cpptools",
"editor.formatOnSave": true,
"C_Cpp.clang_format_fallbackStyle": "{ BasedOnStyle: Google, IndentWidth: 2, TabWidth: 2}"

### 참고자료
https://dev.to/dhanu0510/how-to-configure-c-code-formatting-in-visual-studio-code-4d5m

**Comment by chanhihi** [comment]
확인했습니다. 저는 적용했습니다 !

**Comment by cjho0316** [comment]
감사합니다. 구글스타일에 맞추게 되어서, 구글 입사에 한발 다가가게 되었습니다.
